CREATE USER user_infoed WITH ENCRYPTED PASSWORD '12345';
GRANT ALL PRIVILEGES ON DATABASE projeto_infoeducacao TO user_infoed;
GRANT ALL ON SCHEMA public TO user_infoed;
ALTER SCHEMA public OWNER TO user_infoed;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_infoed;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user_infoed;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO user_infoed;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO user_infoed;

CREATE TABLE conquistas (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE usuarios (
    cduser SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE ranqueamento (
    id SERIAL PRIMARY KEY,
    cduser INTEGER NOT NULL,
    materia VARCHAR(100) NOT NULL,
    serie VARCHAR(50) NOT NULL,
    pontos INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (cduser) REFERENCES usuarios(cduser) ON DELETE CASCADE
);

CREATE TABLE usuarios_conquistas (
    id SERIAL PRIMARY KEY,
    cduser INTEGER NOT NULL,
    iduser INTEGER NOT NULL,
    data_conquista TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cduser) REFERENCES usuarios(cduser) ON DELETE CASCADE,
    FOREIGN KEY (iduser) REFERENCES conquistas(id) ON DELETE CASCADE
);